language: python

os:
  - linux

python:
  - "2.7"
  - "3.6"

before_install:
  - "pip install astropy"
  - "pip install coveralls"
  - "pip install pytest-cov"

install:
  - "python setup.py install"

script:
  - "pytest --cov=pwv_kpno/"

after_success:
  - "coveralls"
